export const AUTH_SERVICE = 'AUTH_SERVICE';
export const PROGRAMS_SERVICE = 'PROGRAMS_SERVICE';
export const CALENDAR_SERVICE = 'CALENDAR_SERVICE';
export const FACILITIES_SERVICE = 'FACILITIES_SERVICE';
export const TEACHING_SERVICE = 'TEACHING_SERVICE';
export const ENROLLMENTS_SERVICE = 'ENROLLMENTS_SERVICE';
export const ASSESSMENTS_SERVICE = 'ASSESSMENTS_SERVICE';

export const NATS_SERVICE = 'NATS_SERVICE';